import { existsSync } from 'node:fs';
import { join } from 'node:path';

/**
 * Screenshots are generated by `npm run demo:screenshots` (scripts/capture-
 * screenshots.ts), which renders each demo's real /preview/<slug> markup and
 * captures it, into public/demos/<slug>/. Until they exist, the UI renders a
 * designed placeholder rather than a broken image — and upgrades itself the
 * moment a file appears.
 *
 * Server-side only: this runs during static generation, never in the browser.
 */
export function hasScreenshot(publicPath: string): boolean {
  return existsSync(join(process.cwd(), 'public', publicPath.replace(/^\//, '')));
}
